# Generated by Django 3.2.3 on 2021-10-27 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_project_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_date',
        ),
    ]
