# Generated by Django 3.2.3 on 2021-10-31 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_project_project_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_date',
        ),
    ]
